name: Deploy React Frontend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::093207963200:role/git-hub-oidc
          aws-region: us-east-1

      - name: Run deployment commands on EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=InstanceIds,Values=i-01579d8c01a88318f" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy FastAPI Backend" \
            --parameters 'commands=[
              "cd ~/fastapi",
              "PIDS=$(pgrep -f uvicorn || true)",
              "if [ -n \"$PIDS\" ]; then sudo kill -9 $PIDS; fi",
              "sleep 5",
              "git fetch -p",
              "git pull origin main",
              "source venv/bin/activate",
              "pip install -r requirements.txt",
              "nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips=\"*\" > app.log 2>&1 &"
            ]'
